package logbook;

public enum Intensity {
    LOW, MODERATELOW, MODERATE, MODERATEHIGH, HIGH;
}

// I WANT TO USE THIS ENUM CLASS BUT IT DOESN'T WORK WELL WITH SAVING/LOADING
// CAN YOU CONVERT STRING INTO ENUM???
